### ISSUE TITLE
it's overriding window.self variable

### ISSUE THREAD

**Issue by sasawant** [yakovlevga/letterpic#2]
It's a nice plugin. 
Found one critical issue. It's overriding the window.self variable, and thus my other js libraries (or any other plugin which depends on window.self object) are not working correctly.
Please check line no. 36 in jquery.letterpic.js.
It should be "**var self = this;** "

**Comment by yakovlevga** [comment]
@sasawant, thanks a lot for noticing this typo! I fixed it.

**Comment by sasawant** [comment]
Thanks a lot :-)
