### ISSUE TITLE
Square support

### ISSUE THREAD

**Issue by JamoCA** [yakovlevga/letterpic#3]
**[FEATURE REQUEST]** The avatar images on many of my projects are displayed using square shapes and occasionally have slightly rounded corners.  In some UIs, the profile image may appear as a top-hanging tab w/rounded corners only on the bottom.  (I noticed GitHub uses square avatars w/slightly rounded corners.)  Would it be difficult to add square and corner-rounding options?  Thanks.

**Comment by yakovlevga** [comment]
Hi! You could apply any additional styles you want by custom css rules.
By default letterpic generates square canvas, and then you could add border-radius property to element.
[Check this example, hope  it helps](https://jsfiddle.net/knjx4x1b/1/)
