### ISSUE TITLE
Not working inside hidden element, eg. tab

### ISSUE THREAD

**Issue by ghost** [yakovlevga/letterpic#4]
Hi, this is great and really useful. I'm using the <canvas> HTML method, but the pics won't display in an initially hidden element; in my case a Bootstrap tab. I have tried to initialize the letterpic plugin after the tab is shown, but they still won't display. Any ideas what I can do to get them to show up?

**Comment by ghost** [comment]
Edit, figured it out...
[Demo](http://xcartmods.com/letterpics.html)

**Comment by yakovlevga** [comment]
Hi, is your problem solved?

**Comment by ghost** [comment]
Yes I think so.
Thanks for the great plugin, really useful for review avatars that don't have Gravatar images :)

**Comment by yakovlevga** [comment]
You are wellcome 👍 
Happy, you like it :)
