### ISSUE TITLE
More than 19 colors/gradients = "TypeError: Cannot read property '0' of undefined"

### ISSUE THREAD

**Issue by JamoCA** [yakovlevga/letterpic#5]
Using default options on a webpage that has more than 19 unique users, I encountered a "TypeError: Cannot read property '0' of undefined".  This error caused only the first 19 icons to be generated and everything after was an unrendered invisible DIV.  If I disable the gradient option and use `fill: 'color'`, no error is throw, but all users over the count of 19 appear on a black background.

Is this a bug or are developers required to identify the maximum unique users being displayed and specify an array of colors that meets or exceeds that amount? (I was under the impression that additional icon colors would start over at the beginning of the array of colors.)

Thanks.

**Comment by yakovlevga** [comment]
Thanks for the report 👍  
That was a bug, fixed now.
